

# H2
spring:
  datasource:
    password:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true




## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
